=== HellInsider/Shopping-Mall-Maps/resources/MapInfoXMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	xmlns:myx="MapInfoXMLSchema"
	targetNamespace="MapInfoXMLSchema" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Info">
		<xs:complexType>
			<xs:sequence maxOccurs="1">
				<xs:element name="size" type ="xs:unsignedInt" />
				<xs:sequence>
					<xs:element ref="myx:InfoLine" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name ="InfoLine">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SVG_ID" type ="xs:string" />
				<xs:element name="short_name" type ="xs:string" />
				<xs:element name="is_a_shop" type="xs:boolean" />
				<xs:element name="short_info" type ="xs:string" minOccurs="0" />
				<xs:element name="opens" type ="xs:time" minOccurs="0" />
				<xs:element name="closes" type ="xs:time" minOccurs="0" />
				<xs:element name="full_info" type ="xs:string" minOccurs="0" />
				<xs:element ref ="myx:coord" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="coord">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="x" type ="xs:double" />
				<xs:element name="y" type ="xs:double" />
			</xs:sequence>
		</xs:complexType>	
	</xs:element> 
	
</xs:schema>

=== HellInsider/Shopping-Mall-Maps/resources/xml_from_excel_backup.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns1:Info xmlns:ns1="MapInfoXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="MapInfoXMLSchema MapInfoXMLSchema.xsd">
	<size>14</size>
	<ns1:InfoLine>
		<SVG_ID>1_shop_6</SVG_ID>
		<short_name>cabinet</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>I've made it look like a description</short_info>
		<opens>09:05:00.000</opens>
		<closes>19:05:00.000</closes>
		<full_info>The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!
The best shop ever!</full_info>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>1_shop_4</SVG_ID>
		<short_name>his brother's room</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>The standard Lorem Ipsum passage, used since the 1500s</short_info>
		<opens>09:05:00.000</opens>
		<closes>19:05:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>1_shop_3</SVG_ID>
		<short_name>Yakov's room</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>Lorem ipsum dolor sit amet,</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>1_toilet_1</SVG_ID>
		<short_name>toilet</short_name>
		<is_a_shop>false</is_a_shop>
		<short_info> consectetur adipiscing elit, </short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>1_shop_2</SVG_ID>
		<short_name>bathroom</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>sed do eiusmod tempor incididunt</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>1_shop_1</SVG_ID>
		<short_name>kitchen</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info> ut labore et dolore magna aliqua. </short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_shop_4</SVG_ID>
		<short_name>big shop</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>Ut enim ad minim veniam,</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_shop_101</SVG_ID>
		<short_name>sophisticated shaped shop</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info> quis nostrud exercitation ullamco</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_shop_104</SVG_ID>
		<short_name>just a shop</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info> laboris nisi ut aliquip ex ea commodo</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_shop_103</SVG_ID>
		<short_name>another shop</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info> consequat. Duis aute irure dolor</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_shop_102</SVG_ID>
		<short_name>and another shop</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info> in reprehenderit in voluptate </short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_shop_5</SVG_ID>
		<short_name>bizarre filled shop</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>velit esse cillum dolore eu fugiat nulla pariatur</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>3_shop_201</SVG_ID>
		<short_name>shop in the trees</short_name>
		<is_a_shop>true</is_a_shop>
		<short_info>. Excepteur sint occaecat cupidatat non proident, </short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
	<ns1:InfoLine>
		<SVG_ID>2_toilet_101</SVG_ID>
		<short_name>toilet</short_name>
		<is_a_shop>false</is_a_shop>
		<short_info>sunt in culpa qui officia deserunt mollit anim id est laborum.</short_info>
		<opens>09:00:00.000</opens>
		<closes>21:00:00.000</closes>
	</ns1:InfoLine>
</ns1:Info>
